### ISSUE TITLE
内存使用量飙升

### ISSUE THREAD

**Issue by siminx** [Sjj1024/s-hub#2]
打开软件后，在我的资源和帮助反馈这2个菜单之间反复切换，只点菜单不做其他任何事，内存使用量飙升，一段时间不用，内存使用量也不减少。
![image](https://github.com/Sjj1024/file-hub/assets/22373408/c356612b-fc1c-4046-ad5d-4649c557c38c)

**Comment by Sjj1024** [comment]
你的是win几的系统啊？我的才27M内存
![image](https://github.com/Sjj1024/file-hub/assets/48399687/c0f76d4d-c7fc-421f-99a9-7482c72b83c4)
