### ISSUE TITLE
会封号吗

### ISSUE THREAD

**Issue by proteincontent** [Sjj1024/s-hub#9]
![image](https://github.com/user-attachments/assets/d4727fd7-b63a-43ba-b9c0-1dac2d0af14b)
![image](https://github.com/user-attachments/assets/4097e9ee-f508-4f48-8f97-1d3ebe1a113c)
请问，为什么视频好像也是播放不了的？

**Comment by Sjj1024** [comment]
不会封号的，挂个代理试试
